// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Prefix prefix
//
// swagger:model Prefix
type Prefix struct {

	// prefix
	Prefix string `json:"prefix,omitempty"`
}

// Validate validates this prefix
func (m *Prefix) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this prefix based on context it is used
func (m *Prefix) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Prefix) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Prefix) UnmarshalBinary(b []byte) error {
	var res Prefix
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
