version: '3'

services:
  api:
    build:
      context: api
    image: alex129/web
    restart: always
    ports:
        - "8080:8080"
    environment:
      - IPv4LOCALADDR=1.1.1.1
      - IPAM=ipam:1034
      - PORT=:8080
      - DB_URL=postgres://postgres:postgresql@postgresdb:5432/tunnelbroker?sslmode=disable
      - BROKER_CONN="amqp://guest:guest@localhost:5672/"
      - QUEUENAME=6in4
      - COOKIEKEY1=my_secret_key1
      - COOKIEKEY2=my_secret_key2
  ipam:
    build:
      context: ipam
    image: alex129/ipam
    restart: always
    environment:
      - PORT=1034
      - DB_URL=postgres://postgres:postgresql@postgresdb:5432/tunnelbroker?sslmode=disable
  postgresdb:
    image: postgres
    tty: true
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=tunnelbroker
