version: '3'

services:
  api:
    build:
      context: api
    image: alex129/api
    restart: always
    ports:
        - "8080:8080"
    environment:
      - IPv4LOCALADDR=95.213.189.130
      - IPAM=ipam:1034
      - PORT=:8080
      - DB_URL=postgres://postgres:postgresql@postgresdb:5432/tunnelbroker?sslmode=disable
      - BROKER_CONN=amqp://brokeruser:brokerpass@rabbitmq:5672/
      - QUEUENAME=6in4
      - COOKIEKEY1=my_secret_key1
      - COOKIEKEY2=my_secret_key2
  ipam:
    build:
      context: ipam
    image: alex129/ipam
    restart: always
    environment:
      - PORT=1034
      - DB_URL=postgres://postgres:postgresql@postgresdb:5432/tunnelbroker?sslmode=disable
  postgresdb:
    image: postgres
    tty: true
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=tunnelbroker
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=brokeruser
      - RABBITMQ_DEFAULT_PASS=brokerpass
    ports:
      - 5672:5672
      - 15672:15672