// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReleaseOKCode is the HTTP code returned for type DeleteReleaseOK
const DeleteReleaseOKCode int = 200

/*
DeleteReleaseOK Prefix sucessfully released

swagger:response deleteReleaseOK
*/
type DeleteReleaseOK struct {
}

// NewDeleteReleaseOK creates DeleteReleaseOK with default headers values
func NewDeleteReleaseOK() *DeleteReleaseOK {

	return &DeleteReleaseOK{}
}

// WriteResponse to the client
func (o *DeleteReleaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteReleaseBadRequestCode is the HTTP code returned for type DeleteReleaseBadRequest
const DeleteReleaseBadRequestCode int = 400

/*
DeleteReleaseBadRequest Bad request

swagger:response deleteReleaseBadRequest
*/
type DeleteReleaseBadRequest struct {
}

// NewDeleteReleaseBadRequest creates DeleteReleaseBadRequest with default headers values
func NewDeleteReleaseBadRequest() *DeleteReleaseBadRequest {

	return &DeleteReleaseBadRequest{}
}

// WriteResponse to the client
func (o *DeleteReleaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteReleaseInternalServerErrorCode is the HTTP code returned for type DeleteReleaseInternalServerError
const DeleteReleaseInternalServerErrorCode int = 500

/*
DeleteReleaseInternalServerError Internal Server Error

swagger:response deleteReleaseInternalServerError
*/
type DeleteReleaseInternalServerError struct {
}

// NewDeleteReleaseInternalServerError creates DeleteReleaseInternalServerError with default headers values
func NewDeleteReleaseInternalServerError() *DeleteReleaseInternalServerError {

	return &DeleteReleaseInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteReleaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
