// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAcquireCreatedCode is the HTTP code returned for type GetAcquireCreated
const GetAcquireCreatedCode int = 201

/*
GetAcquireCreated Prefix sucessfully acquired

swagger:response getAcquireCreated
*/
type GetAcquireCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetAcquireCreated creates GetAcquireCreated with default headers values
func NewGetAcquireCreated() *GetAcquireCreated {

	return &GetAcquireCreated{}
}

// WithPayload adds the payload to the get acquire created response
func (o *GetAcquireCreated) WithPayload(payload string) *GetAcquireCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get acquire created response
func (o *GetAcquireCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAcquireCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAcquireBadRequestCode is the HTTP code returned for type GetAcquireBadRequest
const GetAcquireBadRequestCode int = 400

/*
GetAcquireBadRequest Bad request

swagger:response getAcquireBadRequest
*/
type GetAcquireBadRequest struct {
}

// NewGetAcquireBadRequest creates GetAcquireBadRequest with default headers values
func NewGetAcquireBadRequest() *GetAcquireBadRequest {

	return &GetAcquireBadRequest{}
}

// WriteResponse to the client
func (o *GetAcquireBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetAcquireInternalServerErrorCode is the HTTP code returned for type GetAcquireInternalServerError
const GetAcquireInternalServerErrorCode int = 500

/*
GetAcquireInternalServerError Internal Server Error

swagger:response getAcquireInternalServerError
*/
type GetAcquireInternalServerError struct {
}

// NewGetAcquireInternalServerError creates GetAcquireInternalServerError with default headers values
func NewGetAcquireInternalServerError() *GetAcquireInternalServerError {

	return &GetAcquireInternalServerError{}
}

// WriteResponse to the client
func (o *GetAcquireInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
