// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAcquireHandlerFunc turns a function with the right signature into a get acquire handler
type GetAcquireHandlerFunc func(GetAcquireParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAcquireHandlerFunc) Handle(params GetAcquireParams) middleware.Responder {
	return fn(params)
}

// GetAcquireHandler interface for that can handle valid get acquire params
type GetAcquireHandler interface {
	Handle(GetAcquireParams) middleware.Responder
}

// NewGetAcquire creates a new http.Handler for the get acquire operation
func NewGetAcquire(ctx *middleware.Context, handler GetAcquireHandler) *GetAcquire {
	return &GetAcquire{Context: ctx, Handler: handler}
}

/*
	GetAcquire swagger:route GET /acquire getAcquire

Get new IPv6 range
*/
type GetAcquire struct {
	Context *middleware.Context
	Handler GetAcquireHandler
}

func (o *GetAcquire) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAcquireParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
