// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetAcquireParams creates a new GetAcquireParams object
//
// There are no default values defined in the spec.
func NewGetAcquireParams() GetAcquireParams {

	return GetAcquireParams{}
}

// GetAcquireParams contains all the bound params for the get acquire operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAcquire
type GetAcquireParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Prefix length
	  Required: true
	  In: query
	*/
	Prefixlen int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAcquireParams() beforehand.
func (o *GetAcquireParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPrefixlen, qhkPrefixlen, _ := qs.GetOK("prefixlen")
	if err := o.bindPrefixlen(qPrefixlen, qhkPrefixlen, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPrefixlen binds and validates parameter Prefixlen from query.
func (o *GetAcquireParams) bindPrefixlen(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("prefixlen", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("prefixlen", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("prefixlen", "query", "int64", raw)
	}
	o.Prefixlen = value

	if err := o.validatePrefixlen(formats); err != nil {
		return err
	}

	return nil
}

// validatePrefixlen carries on validations for parameter Prefixlen
func (o *GetAcquireParams) validatePrefixlen(formats strfmt.Registry) error {

	if err := validate.EnumCase("prefixlen", "query", o.Prefixlen, []interface{}{64, 127}, true); err != nil {
		return err
	}

	return nil
}
