swagger: "2.0"
info:
  version: "1.0.0"
  title: "IPAM service"
  description: "IP address management"

produces:
  - application/json
        
paths:
  /acquire:
    get:
      summary: "Get new IPv6 range"
      parameters:
      - in: query
        name: prefixlen
        description: "Prefix length"
        required: true
        type: integer
        enum: [64, 127]
      responses:
        "201":
          description: "Prefix sucessfully acquired"
          schema:
            $ref: "#/definitions/Prefix"
        "400":
          description: "Bad request"
        "500":
          description: "Internal Server Error"
  /release:
    delete:
      summary: "Release IPv6 range"
      parameters:
      - in: query
        name: prefix
        type: string
        description: "Prefix"
        required: true
        minLength: 14
        maxLength: 41       
      - in: query
        name: prefixlen
        description: "Prefix length"
        required: true
        type: integer
        enum: [64, 127]          
      responses:
        "200":
          description: "Prefix sucessfully released"
        "400":
          description: "Bad request"
        "500":
          description: "Internal Server Error"

definitions: 
  Prefix:
    type: object
    properties: 
      prefix:
        type: string