name: Linters test

on:
  push:
    branches:
      - "*"

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # - name: Extract branch name
      #   run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
      - run: go version
      
      - name: Check out code
        uses: actions/checkout@v4

      - name: Go mod tidy
        run: go mod tidy

      - name: Linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          # install-mode: "goinstall"
          args: -v --timeout=10m --config=.golangci.yml 
          